<?php
    $array_noms = array(
        "DURAND",
        "DUPOND",
        "AMIOT",
        "GENDRON", 
        "CHEVREUIL",
        "ALLAIN",
        "VERON",
        "JACQUIN",
        "TULIN",
        "GARCIA",
        "MARTIN",
        "DUPONT",
        "DURANT",
        "JAURES",
        "JOREZ",
        "DA SILVA",
        "LOPEZ",
        "TRUMP",
        "SCHMIDT",
        "TATCHER",
        "DE GAULLE",
        "TRUCMUCHKWZH",
        "CALVINO",
        "ALI",
        "BABA",
        "RILLETTE",
        "CRETIN",
        "DU MANS",
        "DE TOURS",
        "VAMPIRES",
        "TOTO"
    );
?>